# Global settings applied to the whole site
[build]
  base = "client/"  # Pfad zum Verzeichnis des Projekts, wenn sich Ihr Frontend im "client" Ordner befindet
  publish = "client/dist"  # Stellen Sie sicher, dass das Verzeichnis nach dem Build hier veröffentlicht wird
  command = "npm run build"  # Ihr Build-Befehl

# Redirects
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

# Headers
[[headers]]
  for = "/dist/*.js"
  [headers.values]
  Content-Type = "text/javascript"
